version: '3'

services:
  hass:
    image: homeassistant/home-assistant:2023.8.4
    # user: "1000"
    ports:
      - 8123:8123
    volumes:
      - hass:/config
      - ./configuration.yaml:/config/configuration.yaml
      - ./custom_components:/config/custom_components

volumes:
  hass:
