---
services:
  hass:
    image: homeassistant/home-assistant:2024.9.0
    # user: "1000"
    ports:
      - 8123:8123
    volumes:
      - hass:/config
      - ./configuration.yaml:/config/configuration.yaml
      - ./custom_components:/config/custom_components

volumes:
  hass:
